USE [Comp306]
GO

/****** Object:  Table [dbo].[Cast]    Script Date: 29.05.2022 14:41:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cast](
	[Sid] [bigint] NOT NULL,
	[Pid] [bigint] NOT NULL,
 CONSTRAINT [PK_Cast] PRIMARY KEY CLUSTERED 
(
	[Sid] ASC,
	[Pid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Cast]  WITH CHECK ADD  CONSTRAINT [FK_Cast_People] FOREIGN KEY([Pid])
REFERENCES [dbo].[Actor] ([Pid])
GO

ALTER TABLE [dbo].[Cast] CHECK CONSTRAINT [FK_Cast_People]
GO

ALTER TABLE [dbo].[Cast]  WITH CHECK ADD  CONSTRAINT [FK_Cast_Shows] FOREIGN KEY([Sid])
REFERENCES [dbo].[Shows] ([Id])
GO

ALTER TABLE [dbo].[Cast] CHECK CONSTRAINT [FK_Cast_Shows]
GO

